version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "80:80"
    volumes:
      - ./backend/app:/code/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    depends_on:
      - backend
